# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

actions_path './actions/'
fastlane_require 'pp'
fastlane_require 'fileutils'

default_platform(:mac)

xcodeproj_path = "./App/Date.xcodeproj"

def github_output
  output_path = ENV["GITHUB_OUTPUT"]
  unless output_path
    return nil
  end

  puts `cat #{output_path}` 
  hash = {}
  File.open(output_path) { |f|
    output = f.read
    puts output
    output.each_line { |line|    
      kv = line.split("=")
      unless kv.length >= 2 
          next
      end
    
      hash[kv[0].strip] = kv[1].strip
    }
  }
  
  return hash
end

def tag_from_env
  output = github_output
  unless output
    return nil
  end

  return output["tag"]
end

platform :mac do
  desc "Build release build and notarize"
  lane :bump do |options|
    increment_build_number_in_xcodeproj(
      xcodeproj: xcodeproj_path 
    )

    tag = tag_from_env
    if tag == nil  
      tag = options[:tag]      
    end 

    if tag != nil && !tag.empty?
      version = tag[1..-1]
      increment_version_number_in_xcodeproj(
        version_number: version,
        xcodeproj: xcodeproj_path 
      )
    end
  end 

  desc "Build release build and notarize"
  lane :release do |options|
    output_directory = "build"

    # Remove build dir before build 
    FileUtils.rm_rf(File.join(git_repo_root, output_directory))

    build_app(
      scheme: "Date",
      output_directory: output_directory,
      export_method: "developer-id",
      project: xcodeproj_path,
      configuration: "Release",
      clean: true
    )

    # apply these values via ENV
    # - 'Apple ID username' → FL_NOTARIZE_USERNAME
    # - 'Apple ID password' → FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
    # - 'Team ID' → FL_NOTARIZE_ASC_PROVIDER
    # https://github.com/fastlane/fastlane/blob/950bb820237d52e15690408083e328f739ac0ef3/fastlane/lib/fastlane/actions/notarize.rb#L63
    notarize(
      package: "build/Date.app",
      use_notarytool: true,
      print_log: true,
      bundle_id: "net.cyan-stivy.Date",
    )
  end
end
